import Footer from './components/Footer'
import Header from './components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Till-App @Martin Garcia</title>
      </head>
      <body className={inter.className}>
        <header><Header></Header></header>
        {children}
      <footer><Footer></Footer></footer>
      </body>
    </html>
  )
}
